languageCode = "en-us"
title = "rzymek's rumblings"
baseURL = "https://rzymek.github.io/"
theme = "beautifulhugo"

[Params]
    logo = "img/rzymek.jpg"
[Author]
  name = "Krzysiek Rzymkowski"
  email = "rzymek@gmail.com"
  github = "rzymek"
